Content-Security-Policy = """
  default-src 'self';
  script-src 'self' 'unsafe-inline';
  style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
  font-src 'self' https://fonts.gstatic.com data:;
  img-src 'self' data: https:;
  media-src 'self' data:;
  frame-src https://www.youtube.com/;
  connect-src 'self';
"""
